training_args:
 per_device_train_batch_size: 1
 per_device_eval_batch_size: 8
 gradient_accumulation_steps: 16
 num_train_epochs: 30
 fp16: True
 strategy: "epoch"
 optim: "adamw_torch"
 logging_steps: 10
 learning_rate: 1e-4
 warmup_ratio: 0.05
 metric_for_best_model: "f1"

lora_args:
  r: 8
  target_modules:
      - "q_proj"
      - "v_proj"
  lora_alpha: 32
  lora_dropout: 0.1
